### PR TITLE
Added KeccakP-800 and KeccakP-1600 implementation for the ARM AArch64 

### PR DESCRIPTION
**Pull request by andrehcmoraes**
ARMv8 uses the new 64-bit ARM architecture called AArch64, which features a new syntax for vector instructions. Unfortunately, this new syntax has no legacy support, and all existing code in ARMV7 NEON has to be ported.

I implemented the KeccakP-800 and KeccakP-1600 instances in this branch based on the ARMv7 NEON implementation and following the SnP interface guidelines.

### CODE REVIEW

**Comment by gvanas** [comment]
Hi Andre,

Thanks for this nice contribution!

Just two comments before we merge:

1. Did you test your implementation using testSnP()? (I don't have access to such an ARM platform…)
2. Why the "bi" in the folder name? We use this abbreviation for bit interleaving (typically 64-bit lanes on a 32-bit platform), which seems not the case here. So I would suggest to rename the folder into "Optimized64AsmARM".

Kind regards,
Gilles

**Comment by andrehcmoraes** [comment]
Hello Gilles, 

1. I tested it using an excerpt of `testKeyakv2()` in a separate repository. I just tested it with `testSnP()`, and I found a bug in `KeccakP1600_Initialize()`, which I have fixed in the latest commit. It now runs both test functions `testKeyakv2()` and `testSnP()` with no errors.
2. I must confess I had simply copy/pasted "Optimized32biAsmARM" and replaced "32" with "64". I have now renamed the folders to "Optimized64AsmARM".

I have also added a proper target for ARMv8A in the `Makefile.build` in the latest commit. Unfortunately, the `make ARMv8A/KeccakTests` command won't work without commenting lines 65-67 in [Tests/timing.h](https://github.com/gvanas/KeccakCodePackage/blob/master/Tests/timing.h). since there is no specific code for ARMv8 right now.

**Comment by gvanas** [comment]
Perfect, thanks!

If you know how to add support for cycle measurement on ARMv8, that would be great… :-)

**Comment by dfaranha** [comment]
Dear Gilles,

The approach we are using for cycle counting in ARMv8 is described here (kernel module + userland code):
https://zhiyisun.github.io/2016/03/02/How-to-Use-Performance-Monitor-Unit-(PMU)-of-64-bit-ARMv8-A-in-Linux.html

**Pull request merged**
